/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ArchitectureOverview: typeof import('./components/content/ArchitectureOverview.vue')['default']
    BulletList: typeof import('./components/content/BulletList.vue')['default']
    CalloutBox: typeof import('./components/content/CalloutBox.vue')['default']
    CodeBlock: typeof import('./components/CodeBlock.vue')['default']
    Container: typeof import('./components/layout/Container.vue')['default']
    DesignPrinciples: typeof import('./components/content/DesignPrinciples.vue')['default']
    DetailCard: typeof import('./components/DetailCard.vue')['default']
    DetailCards: typeof import('./components/DetailCards.vue')['default']
    GettingStarted: typeof import('./components/content/GettingStarted.vue')['default']
    HeroSection: typeof import('./components/content/HeroSection.vue')['default']
    MarzipansImpact: typeof import('./components/content/MarzipansImpact.vue')['default']
    MarzipansPhilosophy: typeof import('./components/content/MarzipansPhilosophy.vue')['default']
    MarzipanSummary: typeof import('./components/content/MarzipanSummary.vue')['default']
    QuickActions: typeof import('./components/layout/QuickActions.vue')['default']
    RoadmapVisualizer: typeof import('./components/content/RoadmapVisualizer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./components/content/SectionHeader.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    ValueProposition: typeof import('./components/content/ValueProposition.vue')['default']
    WhoIsMarzipanFor: typeof import('./components/content/WhoIsMarzipanFor.vue')['default']
  }
}
