/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/contribute': RouteRecordInfo<'/contribute', '/contribute', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/docs/[...all]': RouteRecordInfo<'/docs/[...all]', '/docs/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/gettingStarted': RouteRecordInfo<'/gettingStarted', '/gettingStarted', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/license/': RouteRecordInfo<'/license/', '/license', Record<never, never>, Record<never, never>>,
    '/license/philosophy': RouteRecordInfo<'/license/philosophy', '/license/philosophy', Record<never, never>, Record<never, never>>,
    '/roadmap': RouteRecordInfo<'/roadmap', '/roadmap', Record<never, never>, Record<never, never>>,
  }
}
